name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]   # change to "master" if your default branch is master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Build and Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: fullstack-web        # Cloud Run service name
          region: ${{ secrets.GCP_REGION }}
          source: .                     # deploy current repo source
          allow_unauthenticated: true   # public URL (omit if you want private)
